# Generated by Django 4.2.8 on 2023-12-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('questionnaires', '0001_initial'),
        ('diagnostics', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECICEPScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='ECICEP score')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('medical_record_id', models.PositiveIntegerField(unique=True, verbose_name='Medical record id')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=20, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('second_last_name', models.CharField(max_length=20, null=True, verbose_name='Second last name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Phone number')),
                ('suicide_attempt', models.BooleanField(verbose_name='Suicide attempt')),
                ('attempt_date', models.DateField(null=True, verbose_name='Attempt date')),
                ('is_ges', models.BooleanField(verbose_name='Is GES')),
                ('signed_ges', models.BooleanField(verbose_name='Signed GES')),
                ('has_pci', models.BooleanField(verbose_name='Has PCI')),
                ('signed_consent', models.BooleanField(verbose_name='Signed consent')),
                ('in_psychiatric_care', models.BooleanField(verbose_name='In psychiatric care')),
                ('seen_in_consulting', models.BooleanField(verbose_name='Seen in consulting')),
                ('is_pregnant', models.BooleanField(verbose_name='Is pregnant')),
                ('due_date', models.DateField(null=True, verbose_name='Due date')),
                ('has_child_under_five', models.BooleanField(verbose_name='Has child under five years old')),
                ('child_birthdate', models.DateField(null=True, verbose_name='Child birthdate')),
                ('diagnostics', models.ManyToManyField(blank=True, related_name='patients', to='diagnostics.diagnosis', verbose_name='Diagnostics')),
                ('ecicep_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.ecicepscore', verbose_name='ECICEP score')),
                ('groups', models.ManyToManyField(blank=True, related_name='patients', to='groups.group', verbose_name='Groups')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Patient status')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Sex')),
            ],
        ),
        migrations.CreateModel(
            name='PatientQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255, verbose_name='Score')),
                ('observations', models.TextField(verbose_name='Observations')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire', verbose_name='Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientstatus', verbose_name='Patient status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.sex', verbose_name='Sex'),
        ),
    ]
