# Generated by Django 4.2.8 on 2023-12-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('sectors', '0001_initial'),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('medical_record_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Medical record number')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('second_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Second last name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('I', 'Intersexual')], max_length=1, verbose_name='Gender')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('suicide_attempt', models.BooleanField(default=False, verbose_name='Suicide attempt')),
                ('attempt_date', models.DateField(blank=True, null=True, verbose_name='Attempt date')),
                ('is_ges', models.BooleanField(default=False, verbose_name='Is GES')),
                ('signed_ges', models.BooleanField(default=False, verbose_name='Signed GES')),
                ('has_pci', models.BooleanField(default=False, verbose_name='Has PCI')),
                ('signed_consent', models.BooleanField(default=False, verbose_name='Signed consent')),
                ('in_psychiatric_care', models.BooleanField(default=False, verbose_name='In psychiatric care')),
                ('seen_in_consulting', models.BooleanField(default=False, verbose_name='Seen in consulting')),
                ('ecicep_score', models.CharField(blank=True, max_length=2, null=True, verbose_name='ECICEP score')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='Is pregnant')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('has_child_under_five', models.BooleanField(default=False, verbose_name='Has child under five years old')),
                ('child_birthdate', models.DateField(blank=True, null=True, verbose_name='Child birthdate')),
                ('diagnostics', models.ManyToManyField(blank=True, to='diagnostics.diagnosis', verbose_name='Diagnostics')),
                ('groups', models.ManyToManyField(blank=True, to='groups.group', verbose_name='Groups')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.sector', verbose_name='Sector')),
            ],
        ),
    ]
