# Generated by Django 4.2.8 on 2023-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('groups', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnostics',
            field=models.ManyToManyField(blank=True, related_name='patients', to='diagnostics.diagnosis', verbose_name='Diagnostics'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='patients', to='groups.group', verbose_name='Groups'),
        ),
    ]
