# Generated by Django 4.2.8 on 2023-12-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Attendance date')),
                ('attendance_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Attendance recorded')),
                ('attended', models.BooleanField(verbose_name='Attended')),
                ('observations', models.TextField(null=True, verbose_name='Observations')),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient', verbose_name='Patient')),
            ],
        ),
    ]
